name: tml
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python==3.11.6
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - lightning
  - conda-forge::pandas
  - conda-forge::scikit-learn
  - conda-forge::matplotlib
  - seaborn
  - conda-forge::tensorboard

