[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tml"
version = "0.1.0"
description = "A python package. "
readme = "README.md"
requires-python = ">=3.11"
# license = {file = "LICENSE.txt"}

authors = [
    {name = "Ehsan Karimiara", email = "e.karimiara@gmail.com" }
    ]

dependencies = [
#    "pytorch == 2.5.0",
#    "pytorch-cuda == 12.4",
#    "lightning == 2.4",
    "numpy",
#    "pandas",
#    "tensorboard == 2.18",
#    "scikit-learn",
#    "seaborn", 
#    "matplotlib",

    ]

[tool.setuptools]
packages = ["tml"]
